// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtableFamilyUnitMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableFamilyUnitMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "202405311932334_add table FamilyUnitMembers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
