// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addfieldPlantationTypes_IdtotablePlantation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfieldPlantationTypes_IdtotablePlantation));
        
        string IMigrationMetadata.Id
        {
            get { return "202407171358112_add field PlantationTypes_Id to table Plantation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
